In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from scipy.io import loadmat
mat =loadmat("/content/ex7data2.mat")
X=mat["X"]

In [3]:
#initialize the centroids
import random
init_cent=random.sample(range(0,len(X)),3)


In [4]:
init_cent

[211, 113, 153]

In [5]:
centroids=[]
for i in init_cent:
  centroids.append(X[i])
centroids

[array([6.64107248, 3.05998738]),
 array([4.13835915, 1.24780979]),
 array([2.95818429, 1.01887096])]

In [17]:
def calc_dis(x1, x2):
    x1 = np.array(x1)
    x2 = np.array(x2)
    return np.sqrt(np.sum((x1 - x2)**2))

In [7]:
def findclosestCentroid(centroid,X):
  assi_cent=[]
  for i in X:
    distance=[]
    for j in centroid:
      distance.append(calc_dis(i,j))
    assi_cent.append(np.argmin(distance))
  return assi_cent



In [8]:
findclosestCentroid(centroids,X)

[np.int64(2),
 np.int64(0),
 np.int64(0),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(0),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(0),
 np.int64(2),
 np.int64(0),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(1),
 np.int64(1),
 np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.int64(2),
 np.in

In [9]:
#mean of the observation falling in each cluster category
def new_centroid(centroid,X):
  new_centroids=[]
  new_df=pd.concat([pd.DataFrame(X),pd.DataFrame(centroid,columns=['centroid'])],axis=1)
  for c in set(new_df['centroid']):
    current_cluster=new_df[new_df['centroid']==c][new_df.columns[:-1]]
    new_mean=current_cluster.mean(axis=0)
    new_centroids.append(new_mean)
  return new_centroids

In [19]:
for i in range(10):
  obs_cen=findclosestCentroid(centroids,X)
  centroids=new_centroid=(obs_cen,X)
  plt.figure()
  plt.scatter(np.array(centroids)[:,0],np.array(centroids)[:,1],color='black')
  plt.scatter(X[:,0],X[:,1])
  plt.show()


ValueError: operands could not be broadcast together with shapes (2,) (300,) 

In [14]:
centroids

[array([6.64107248, 3.05998738]),
 array([4.13835915, 1.24780979]),
 array([2.95818429, 1.01887096])]

In [21]:
##image Compression
import cv2
img=cv2.imread("/content/sample.jpg")
img.shape

(200, 200, 3)

In [23]:

img = (img/255).reshape(200*200, 3)

In [ ]:
random_index = random.sample(range(0, len(im)), 10)